name: Build Flutter APK & AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ✅ Android SDK setup
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Install API 35
      - name: Install API 35
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Get dependencies
        run: flutter pub get

      # ✅ Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-key.jks

      # 🔥 NEW STEP (MOST IMPORTANT)
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
          echo "storeFile=upload-key.jks" >> android/app/key.properties

      - name: Clean
        run: flutter clean

      # ✅ Build APK
      - name: Build APK
        run: flutter build apk --release

      # ✅ Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: build/app/outputs/bundle/release/app-release.aab
